apiVersion: apps/v1
kind: Deployment
metadata:
  name: servys-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: servys-app
  template:
    metadata:
      labels:
        app: servys-app
    spec:
      containers:
      - name: servys-app
        image: servymcserverson:latest
        ports:
        - containerPort: 80
